### ISSUE TITLE
os-tests CENTOS7 pointing to invalid path

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/sdk-eval-toolset#1]
The script is trying to point to a path that does not exist
cd Python_Wrapper
python PythonWrapperTestApp.py -w Python_Wrapper/Glasswall.py -i ../input -o ../output -c Config.xml -d ../libraries/libglasswall_core2.so

That is the shell script the path  ../libraries/libglasswall_core2.so is wrong.
From the directory Python_Wrapper the path to the so should be ../Lib/libglasswall_core2.so
It may even be better to run it back to the original library location, which would be;
../../../libraries/linux

**Comment by safiankhanGW** [comment]
These commands refer to the run.sh file, which is designed to be run inside the created docker container and not within a Linux VM. If host OS is Windows then bat file can be used to build the Linux docker container.
