### ISSUE TITLE
Failure to open PythonWrapperTestApp.py when executing run.sh for the Linux OS tests

### ISSUE THREAD

**Issue by Vinnietram** [filetrust/sdk-eval-toolset#2]
root@18726c43830f:/home/glasswall# ./run.sh
: No such file or directoryn_Wrapper
python3.4: can't open file 'PythonWrapperTestApp.py': [Errno 2] No such file or directory
root@18726c43830f:/home/glasswall# ./run.sh

**Comment by safiankhanGW** [comment]
Resolved with the following changes [https://github.com/filetrust/sdk-eval-toolset/commit/25365ea968ff63d77878e2115dd78bcbb38f5a44](url)
